### ISSUE TITLE
Part SD Card Module has no Schematic or PCB

### ISSUE THREAD

**Issue by Amicussamir** [robertoostenveld/fritzing#1]
Hello.
Great work creating this Fritzing part.

I have noticed that part has no Schematics and PCB views so I have created them.

**Comment by robertoostenveld** [comment]
it would be nice if you could share them, e.g. by making a fork of my "frizing" repository and uploading it there.

**Comment by Amicussamir** [comment]
OK. I will upload new part.

**Comment by Schnazey** [comment]
Was this updated somewhere else?  The part still seems to be missing the schematics and PCB views.

**Comment by robertoostenveld** [comment]
I am not aware of @Amicussamir uploading it anywhere. 

I don't have plans to work on this, but feel free to fork the repository and make improvements.
